/* Generated by re2c 0.13.8.dev on Tue Jan 13 18:41:45 2015 */
#line 1 "input_istream.re"
#include <sstream>

bool lex (std::istringstream & YYCURSOR, const std::streampos YYLIMIT)
{
    std::streampos YYMARKER;
    std::streampos YYCTXMARKER;
#   define YYCTYPE   char
#   define YYFILL(n) {}
    
#line 13 "input_istream.cpp"
{
	YYCTYPE yych;

	if ((YYLIMIT - YYCURSOR.tellg ()) < 13) YYFILL(13);
	yych = YYCURSOR.peek ();
	switch (yych) {
	case 'i':	goto yy4;
	default:	goto yy2;
	}
yy2:
	YYCURSOR.ignore ();
yy3:
#line 11 "input_istream.re"
	{ return false; }
#line 28 "input_istream.cpp"
yy4:
	YYCURSOR.ignore ();
	YYMARKER = YYCURSOR.tellg ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case 'n':	goto yy5;
	default:	goto yy3;
	}
yy5:
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case 't':	goto yy7;
	default:	goto yy6;
	}
yy6:
	YYCURSOR.seekg (YYMARKER);
	goto yy3;
yy7:
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case ' ':	goto yy8;
	default:	goto yy6;
	}
yy8:
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case 'b':	goto yy9;
	default:	goto yy6;
	}
yy9:
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case 'u':	goto yy10;
	default:	goto yy6;
	}
yy10:
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case 'f':	goto yy11;
	default:	goto yy6;
	}
yy11:
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case 'f':	goto yy12;
	default:	goto yy6;
	}
yy12:
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case 'e':	goto yy13;
	default:	goto yy6;
	}
yy13:
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case 'r':	goto yy14;
	default:	goto yy6;
	}
yy14:
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case ' ':	goto yy15;
	default:	goto yy6;
	}
yy15:
	YYCTXMARKER = YYCURSOR.tellg ();
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case '[':	goto yy16;
	default:	goto yy6;
	}
yy16:
	YYCURSOR.ignore ();
	yych = YYCURSOR.peek ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy17;
	default:	goto yy6;
	}
yy17:
	YYCURSOR.ignore ();
	if ((YYLIMIT - YYCURSOR.tellg ()) < 1) YYFILL(1);
	yych = YYCURSOR.peek ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy17;
	case ']':	goto yy19;
	default:	goto yy6;
	}
yy19:
	YYCURSOR.ignore ();
	YYCURSOR.seekg (YYCTXMARKER);
	YYCURSOR.ignore ();
#line 10 "input_istream.re"
	{ return true; }
#line 151 "input_istream.cpp"
}
#line 12 "input_istream.re"

}

int main ()
{
    const char buffer [] = "int buffer [1024]";
    std::istringstream is (buffer);
    return !lex (is, sizeof (buffer));
}
